### ISSUE TITLE
Move to `pyproject.toml`?

### ISSUE THREAD

**Issue by ZedThree** [boutproject/hypnotoad#154]
Having all of the build config in `pyproject.toml` is now well supported, and now even editable installs work without `setup.py` since `pip 22`. PEP 621 defines some standard keys, so people can use new and weird build tools like poetry or flit if they like.

I'm happy to implement this if it would be useful!

**Comment by johnomotani** [comment]
Sounds good @ZedThree - go for it, and thank you!
