### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/hypnotoad#20]
Stupid question, but wouldn't hypnotoad be a better name?

As far as I understand, this is supposed to do basically the same thing as the old hypnotoad (more or less). So a user wouldn't really care whether this is an improved version or a rewrite, it is basically version 2 of hypnotoad.

Thinking from the user perspective, I want hypnotoad, thus I install hypnotoad. Whether that is version 1 or 2 (or 3) doesn't matter that much. Thus I can just `pip install hypnotoad` and get the _best_ (newest) version.

https://pypi.org/project/hypnotoad/ is still available :+1:

**Comment by johnomotani** [comment]
I think I'd agree `hypnotoad` would be better. Thoughts @bendudson @ZedThree?

**Comment by bendudson** [comment]
Yes probably agree. The original IDL hypnotoad is (almost) entirely replaced by this python version, and it's unlikely that the IDL and python versions will be confused.

**Comment by ZedThree** [comment]
I slightly favour `hypnotoad2`, as it is a different project, but I'm happy to go with the consensus of `hypnotoad` :smile:
