### ISSUE TITLE
Options class replacement

### ISSUE THREAD

**Issue by johnomotani** [boutproject/hypnotoad#27]
As discussed here https://github.com/boutproject/hypnotoad/pull/25#discussion_r415644607 there are various issues with using the `options` module for handling settings in `hypnotoad`:

@dschwoerer 
- I just wanted to mention that options pulls in additional dependencies. As options doesn't even seem to have a public bug tracker (same is true for some dependencies) I do worry about pulling that in ...
- `options` allows getting options simply as e.g. `self.options.orthogonal`, but "that is only a few lines [to implement], I [@dschwoerer] did that to drop the dependency on Bunch."

@ZedThree 
- not being able to `deepcopy` 
- removing keys from the passed-in object
- To make the options form in the gui more useful, I think we would want to add some additional features to the options class at any rate:
    - keeping track of documentation
    - expected type of values, allowed values. For example, make refine_method into a drop-down list of the available methods.

A replacement `Options` class would be welcome. Maybe a possibility for something shared with `xBOUT` https://github.com/boutproject/xBOUT/issues/94 https://github.com/boutproject/xBOUT/pull/97?

**Comment by bendudson** [comment]
I agree with the points above. 

In general I think the idea of a persistent / immutable data structure for options is a good one, but options is probably too flexible: It provides too many different ways to update or modify values (mutating or non-mutating? `set`, `push`, `add`, `addflat`), and the distinction between them is not well documented. When seeing it used, it was not always clear to me where values were set, given the multiple levels where defaults can be provided or overridden. It's possible that python is too flexible to enforce a particular mental model of what is going on, but I think it would be nice to have a simpler system. Personally I'd like it to be immutable (no set operations, all changes are effectively deepcopies), or at least allow deep copies.

**Comment by bendudson** [comment]
For modifying nested data structures (e.g. maps containing maps), the JS immer library has a quite nice interface: https://immerjs.github.io/immer/docs/introduction. I don't know how hard that might be to implement in python though, especially with the limitations of python lambdas. Things are simpler if options is a flat dict/map structure, so options can't contain options.

**Comment by johnomotani** [comment]
> Personally I'd like it to be immutable (no set operations, all changes are effectively deepcopies), or at least allow deep copies.

It might actually be nice to have the options be immutable by default, but be able to say that some are allowed to be changed. I think mostly the options have to be set when the `Mesh` object is created (`nx` and `ny` for regions for example) but for nonorthogonal grids there's a subset of options (the `nonorthogonal_*` ones) that can be usefully changed before calling `MeshRegion.distributePointsNonorthogonal` again: the `Mesh.redistributePoints` method and regrid button in #26 demonstrate how this is a useful workflow.

**Comment by johnomotani** [comment]
(not really the ideal place for this, but want to keep it in an open issue somewhere)

https://github.com/boutproject/hypnotoad/pull/24#issuecomment-619859494
> Future wishlist: raise OptionError with name of option as an attribute so we can highlight bad options?

**Comment by bendudson** [comment]
Possibly not ideal, but here's a quick idea of what a replacement could look like:
```
class Options:
    def __init__(self,**kwargs):
        self._data = kwargs
    
    def keys(self):
        return self._data.keys()
    
    def __getitem__(self, key):
        """Access values like dict. Note no __setitem__"""
        return self._data.__getitem__(key)

    def __getattr__(self, key):
        """Access values with .key like Bunch"""
        return self.__getitem__(key)
    
    def using(self, **kwargs):   # "with" would be a good name, but reserved
        """Return a copy, overriding given values"""
        newdata = self._data.copy()
        for key in kwargs:
            newdata[key] = kwargs[key]
        return Options(**newdata)

    def without(self, *omit_keys):
        """Return a copy without the given keys"""
        newdata = {}
        for key, value in self._data.items():
            if key not in omit_keys:
                newdata[key] = value
        return Options(**newdata)
    
    def __str__(self):
        return self._data.__str__()
    
    def __repr__(self):
        return "Options(" + ", ".join([str(key) + "=" + repr(value)
                                       for key, value in self._data.items()]) + ")"
```
obviously with comments, tests. This allows it to be treated as a dictionary (or Bunch, with the __getattr__ method), except that changes don't propagate upstream. For example:
```
a = Options(key=2, test=42)

a["test"] # -> 42
a.test # -> 42

# Create a new Options, adding new keys
b = a.using(test = 3)

b # -> Options(key=2, test=3)

# Create a new Options, omitting some keys
c = a.without("test")
c # -> Options(key=2)

```
