### ISSUE TITLE
Backward compatibility with 'hthe'

### ISSUE THREAD

**Issue by johnomotani** [boutproject/hypnotoad#38]
The poloidal spacing variable `hy` corresponds to `hthe` in the original Hypnotoad, but is defined slightly differently for non-orthogonal grids. For that reason, I named the variable differently, and the variable in the netCDF output files is named `hy`.

The downside of the current implementation is that existing codes may calculate metric coefficients using `hthe` as input. This can be useful as normalisation can be simpler on basic `R` and `hy` (lengths) and `B`, `Bt`, `Bp` (magnetic fields) than on metric coefficients (when `psi` is used as radial coordinate lengths and magnetic field units get mixed up in the coordinate system).

The 'problem' with changed definition of `hy` vs. `hthe` only affects non-orthogonal grids. In practice, I guess there are no production codes depending on the Hypnotoad-1 style non-orthogonal grids, so it is probably not an issue to save `hthe` to the grid files, because in practice no one is depending on the old definition. On the other hand, saving as `hthe` provides better backward-compatibility with codes using orthogonal grids.

So I'd propose to update `hypnotoad` to save the variable as `hthe`. Thoughts @bendudson @ZedThree @bshanahan?

**Comment by johnomotani** [comment]
BTW @bendudson @ZedThree @bshanahan to clarify the question - do you think there's any risk of there being people out there who would be caught out by reading the non-orthogonal `hthe` from grid-files? My suspicion is not, and if so I think it's a no-brainer to make the change in #39, but wanted to check before I do something that might possibly silently cause incorrect results.

**Comment by ZedThree** [comment]
Is it massively different?

I would be surprised if there were very many people using old-hypnotoad non-orthogonal grids that have upgraded to new-hypnotoad. And those that do, I would hope would read the "breaking changes" docs first.

**Comment by bendudson** [comment]
For correctness it would be nice if nonorthogonal grids didn't write hthe, so at least a user has to make an effort to (mis)use a non-orthogonal grid as if it were orthogonal.

**Comment by johnomotani** [comment]
That sounds good. I think the best thing might be to always write `hy` (like we currently do), but add `hthe` only for orthogonal grids. I'll change #39...
