### ISSUE TITLE
Save geqdsk into grid file?

### ISSUE THREAD

**Issue by johnomotani** [boutproject/hypnotoad#70]
Would it be a good idea when creating a grid file from a geqdsk equilibrium file to save the entire geqdsk file into the grid file, e.g. as a massive string? Pro: ensures the geqdsk file can be recovered. Con: grid file is a bit bigger.

**Comment by d7919** [comment]
I think this would be quite nice -- it makes it harder to lose the source data.

**Comment by bendudson** [comment]
Yes, agreed this would be good! Either the original string, or the 1D and 2D quantities as arrays

**Comment by johnomotani** [comment]
I'm working on this now (before I create another grid file that I might want to use!). Am going for saving as a string because (1) it's simpler and (2) it ensures we can get back the original geqdsk file regardless of possible bugs in the reading routines, etc. Only downside is it's not as efficient on space, but geqdsk files aren't big compared to simulation output anyway.

**Comment by d7919** [comment]
I'd vote for the original string so that it is easy to extract as input to other tools if needed.
